"""initial_schema

Revision ID: 0a5a7d730422
Revises: 
Create Date: 2026-02-13 18:18:02.223246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5a7d730422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_history',
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('total_consumption', sa.Float(), nullable=True),
    sa.Column('total_service_fee', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('client_monthly_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('service_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'client_name', name='_month_client_uc')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('fee_clause', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('client_monthly_stats')
    op.drop_table('billing_history')
    # ### end Alembic commands ###
