"""add payment_term to client and contract lines

Revision ID: ef411ec1cdbb
Revises: f7c2d9e41b3a
Create Date: 2026-04-09 12:24:40.002227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef411ec1cdbb'
down_revision: Union[str, Sequence[str], None] = 'f7c2d9e41b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_contract_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_term', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_contract_lines_client_name'))
        batch_op.drop_index(batch_op.f('ix_contract_lines_source'))

    with op.batch_alter_table('client_monthly_detail_stats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('month',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('client_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('bill_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'—'"))
        batch_op.alter_column('service_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'—'"))

    with op.batch_alter_table('client_monthly_notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('month',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('client_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_term', sa.String(), nullable=True))

    with op.batch_alter_table('operation_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('actor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('input_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('output_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('result_ref',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_operation_audit_logs_action_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_audit_logs_actor_created_at'))
        batch_op.create_index(batch_op.f('ix_operation_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_audit_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_audit_logs_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('operation_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_operation_audit_logs_category'))
        batch_op.drop_index(batch_op.f('ix_operation_audit_logs_actor'))
        batch_op.drop_index(batch_op.f('ix_operation_audit_logs_action'))
        batch_op.create_index(batch_op.f('ix_operation_audit_logs_actor_created_at'), ['actor', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_audit_logs_action_created_at'), ['action', 'created_at'], unique=False)
        batch_op.alter_column('metadata_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('result_ref',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('output_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('input_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('actor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('payment_term')

    with op.batch_alter_table('client_monthly_notes', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('client_monthly_detail_stats', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'—'"))
        batch_op.alter_column('bill_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'—'"))
        batch_op.alter_column('client_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('client_contract_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_lines_source'), ['source_type', 'source_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_lines_client_name'), ['client_name'], unique=False)
        batch_op.drop_column('payment_term')

    # ### end Alembic commands ###
